services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:80"
    env_file:
      - ./frontend/.env.development
    depends_on:
      - backend
volumes:
  redis-data:
